sympyで連立方程式を扱うときのメモ

In [18]:
#pip install --upgrade --force-reinstall  git+https://github.com/kanawa12/symcontroltools

In [19]:
import sympy as sp
import control as ct
import symcontroltools as sct
from symcontroltools import dp

# 変数の定義

In [20]:
dim = 3
Ap = sp.Matrix( ap := sp.symbols(r"{a_{p}}_{1:"+str(dim**2 + 1)+"}") ).reshape(dim, dim)
Xp = sp.Matrix( xp := sp.symbols(r"{x_{p}}_{1:"+str(dim + 1)+"}") ).reshape(dim, 1)
Yp = sp.Matrix( yp := sp.symbols(r"{y_{p}}_{1:"+str(dim + 1)+"}") ).reshape(dim, 1)
dp(sp.Tuple(Ap, *ap))
dp( expr1 := sp.Eq(sp.MatMul(Ap, Xp, evaluate=False), Yp, evaluate=False) )
dp( sp.Tuple(Ap, Xp, Yp) )


(Matrix([
[{a_{p}}_{1}, {a_{p}}_{2}, {a_{p}}_{3}],
[{a_{p}}_{4}, {a_{p}}_{5}, {a_{p}}_{6}],
[{a_{p}}_{7}, {a_{p}}_{8}, {a_{p}}_{9}]]), {a_{p}}_{1}, {a_{p}}_{2}, {a_{p}}_{3}, {a_{p}}_{4}, {a_{p}}_{5}, {a_{p}}_{6}, {a_{p}}_{7}, {a_{p}}_{8}, {a_{p}}_{9})

$$\left( \left[\begin{matrix}{a_{p}}_{1} & {a_{p}}_{2} & {a_{p}}_{3}\\{a_{p}}_{4} & {a_{p}}_{5} & {a_{p}}_{6}\\{a_{p}}_{7} & {a_{p}}_{8} & {a_{p}}_{9}\end{matrix}\right], \  {a_{p}}_{1}, \  {a_{p}}_{2}, \  {a_{p}}_{3}, \  {a_{p}}_{4}, \  {a_{p}}_{5}, \  {a_{p}}_{6}, \  {a_{p}}_{7}, \  {a_{p}}_{8}, \  {a_{p}}_{9}\right)$$<details><summary>sympy.srepr()</summary><p>Tuple(ImmutableDenseMatrix([[Symbol('{a_{p}}_{1}'), Symbol('{a_{p}}_{2}'), Symbol('{a_{p}}_{3}')], [Symbol('{a_{p}}_{4}'), Symbol('{a_{p}}_{5}'), Symbol('{a_{p}}_{6}')], [Symbol('{a_{p}}_{7}'), Symbol('{a_{p}}_{8}'), Symbol('{a_{p}}_{9}')]]), Symbol('{a_{p}}_{1}'), Symbol('{a_{p}}_{2}'), Symbol('{a_{p}}_{3}'), Symbol('{a_{p}}_{4}'), Symbol('{a_{p}}_{5}'), Symbol('{a_{p}}_{6}'), Symbol('{a_{p}}_{7}'), Symbol('{a_{p}}_{8}'), Symbol('{a_{p}}_{9}'))</p></details>


Eq(Matrix([
[{a_{p}}_{1}, {a_{p}}_{2}, {a_{p}}_{3}],
[{a_{p}}_{4}, {a_{p}}_{5}, {a_{p}}_{6}],
[{a_{p}}_{7}, {a_{p}}_{8}, {a_{p}}_{9}]])*Matrix([
[{x_{p}}_{1}],
[{x_{p}}_{2}],
[{x_{p}}_{3}]]), Matrix([
[{y_{p}}_{1}],
[{y_{p}}_{2}],
[{y_{p}}_{3}]]))

$$\left[\begin{matrix}{a_{p}}_{1} & {a_{p}}_{2} & {a_{p}}_{3}\\{a_{p}}_{4} & {a_{p}}_{5} & {a_{p}}_{6}\\{a_{p}}_{7} & {a_{p}}_{8} & {a_{p}}_{9}\end{matrix}\right] \left[\begin{matrix}{x_{p}}_{1}\\{x_{p}}_{2}\\{x_{p}}_{3}\end{matrix}\right] = \left[\begin{matrix}{y_{p}}_{1}\\{y_{p}}_{2}\\{y_{p}}_{3}\end{matrix}\right]$$<details><summary>sympy.srepr()</summary><p>Equality(MatMul(ImmutableDenseMatrix([[Symbol('{a_{p}}_{1}'), Symbol('{a_{p}}_{2}'), Symbol('{a_{p}}_{3}')], [Symbol('{a_{p}}_{4}'), Symbol('{a_{p}}_{5}'), Symbol('{a_{p}}_{6}')], [Symbol('{a_{p}}_{7}'), Symbol('{a_{p}}_{8}'), Symbol('{a_{p}}_{9}')]]), ImmutableDenseMatrix([[Symbol('{x_{p}}_{1}')], [Symbol('{x_{p}}_{2}')], [Symbol('{x_{p}}_{3}')]])), ImmutableDenseMatrix([[Symbol('{y_{p}}_{1}')], [Symbol('{y_{p}}_{2}')], [Symbol('{y_{p}}_{3}')]]))</p></details>


(Matrix([
[{a_{p}}_{1}, {a_{p}}_{2}, {a_{p}}_{3}],
[{a_{p}}_{4}, {a_{p}}_{5}, {a_{p}}_{6}],
[{a_{p}}_{7}, {a_{p}}_{8}, {a_{p}}_{9}]]), Matrix([
[{x_{p}}_{1}],
[{x_{p}}_{2}],
[{x_{p}}_{3}]]), Matrix([
[{y_{p}}_{1}],
[{y_{p}}_{2}],
[{y_{p}}_{3}]]))

$$\left( \left[\begin{matrix}{a_{p}}_{1} & {a_{p}}_{2} & {a_{p}}_{3}\\{a_{p}}_{4} & {a_{p}}_{5} & {a_{p}}_{6}\\{a_{p}}_{7} & {a_{p}}_{8} & {a_{p}}_{9}\end{matrix}\right], \  \left[\begin{matrix}{x_{p}}_{1}\\{x_{p}}_{2}\\{x_{p}}_{3}\end{matrix}\right], \  \left[\begin{matrix}{y_{p}}_{1}\\{y_{p}}_{2}\\{y_{p}}_{3}\end{matrix}\right]\right)$$<details><summary>sympy.srepr()</summary><p>Tuple(ImmutableDenseMatrix([[Symbol('{a_{p}}_{1}'), Symbol('{a_{p}}_{2}'), Symbol('{a_{p}}_{3}')], [Symbol('{a_{p}}_{4}'), Symbol('{a_{p}}_{5}'), Symbol('{a_{p}}_{6}')], [Symbol('{a_{p}}_{7}'), Symbol('{a_{p}}_{8}'), Symbol('{a_{p}}_{9}')]]), ImmutableDenseMatrix([[Symbol('{x_{p}}_{1}')], [Symbol('{x_{p}}_{2}')], [Symbol('{x_{p}}_{3}')]]), ImmutableDenseMatrix([[Symbol('{y_{p}}_{1}')], [Symbol('{y_{p}}_{2}')], [Symbol('{y_{p}}_{3}')]]))</p></details>


In [21]:
dp(expr1.free_symbols)

{{a_{p}}_{1},
 {a_{p}}_{2},
 {a_{p}}_{3},
 {a_{p}}_{4},
 {a_{p}}_{5},
 {a_{p}}_{6},
 {a_{p}}_{7},
 {a_{p}}_{8},
 {a_{p}}_{9},
 {x_{p}}_{1},
 {x_{p}}_{2},
 {x_{p}}_{3},
 {y_{p}}_{1},
 {y_{p}}_{2},
 {y_{p}}_{3}}

$$\left\{{a_{p}}_{1}, {a_{p}}_{2}, {a_{p}}_{3}, {a_{p}}_{4}, {a_{p}}_{5}, {a_{p}}_{6}, {a_{p}}_{7}, {a_{p}}_{8}, {a_{p}}_{9}, {x_{p}}_{1}, {x_{p}}_{2}, {x_{p}}_{3}, {y_{p}}_{1}, {y_{p}}_{2}, {y_{p}}_{3}\right\}$$<details><summary>sympy.srepr()</summary><p>{Symbol('{a_{p}}_{4}'), Symbol('{y_{p}}_{1}'), Symbol('{a_{p}}_{1}'), Symbol('{a_{p}}_{9}'), Symbol('{y_{p}}_{2}'), Symbol('{a_{p}}_{2}'), Symbol('{x_{p}}_{3}'), Symbol('{a_{p}}_{6}'), Symbol('{x_{p}}_{1}'), Symbol('{a_{p}}_{8}'), Symbol('{a_{p}}_{7}'), Symbol('{y_{p}}_{3}'), Symbol('{a_{p}}_{3}'), Symbol('{x_{p}}_{2}'), Symbol('{a_{p}}_{5}')}</p></details>


In [22]:
exprs1 = {"expr": expr1, "syms": expr1.free_symbols}
# または
exprs1 = {"expr": expr1, "syms": (*ap, *xp)}
dp(exprs1)

{'expr': Eq(Matrix([
 [{a_{p}}_{1}, {a_{p}}_{2}, {a_{p}}_{3}],
 [{a_{p}}_{4}, {a_{p}}_{5}, {a_{p}}_{6}],
 [{a_{p}}_{7}, {a_{p}}_{8}, {a_{p}}_{9}]])*Matrix([
 [{x_{p}}_{1}],
 [{x_{p}}_{2}],
 [{x_{p}}_{3}]]), Matrix([
 [{y_{p}}_{1}],
 [{y_{p}}_{2}],
 [{y_{p}}_{3}]])),
 'syms': ({a_{p}}_{1},
  {a_{p}}_{2},
  {a_{p}}_{3},
  {a_{p}}_{4},
  {a_{p}}_{5},
  {a_{p}}_{6},
  {a_{p}}_{7},
  {a_{p}}_{8},
  {a_{p}}_{9},
  {x_{p}}_{1},
  {x_{p}}_{2},
  {x_{p}}_{3})}

$$\left\{ \mathtt{\text{expr}} : \left[\begin{matrix}{a_{p}}_{1} & {a_{p}}_{2} & {a_{p}}_{3}\\{a_{p}}_{4} & {a_{p}}_{5} & {a_{p}}_{6}\\{a_{p}}_{7} & {a_{p}}_{8} & {a_{p}}_{9}\end{matrix}\right] \left[\begin{matrix}{x_{p}}_{1}\\{x_{p}}_{2}\\{x_{p}}_{3}\end{matrix}\right] = \left[\begin{matrix}{y_{p}}_{1}\\{y_{p}}_{2}\\{y_{p}}_{3}\end{matrix}\right], \  \mathtt{\text{syms}} : \left( {a_{p}}_{1}, \  {a_{p}}_{2}, \  {a_{p}}_{3}, \  {a_{p}}_{4}, \  {a_{p}}_{5}, \  {a_{p}}_{6}, \  {a_{p}}_{7}, \  {a_{p}}_{8}, \  {a_{p}}_{9}, \  {x_{p}}_{1}, \  {x_{p}}_{2}, \  {x_{p}}_{3}\right)\right\}$$<details><summary>sympy.srepr()</summary><p>{'expr': Equality(MatMul(ImmutableDenseMatrix([[Symbol('{a_{p}}_{1}'), Symbol('{a_{p}}_{2}'), Symbol('{a_{p}}_{3}')], [Symbol('{a_{p}}_{4}'), Symbol('{a_{p}}_{5}'), Symbol('{a_{p}}_{6}')], [Symbol('{a_{p}}_{7}'), Symbol('{a_{p}}_{8}'), Symbol('{a_{p}}_{9}')]]), ImmutableDenseMatrix([[Symbol('{x_{p}}_{1}')], [Symbol('{x_{p}}_{2}')], [Symbol('{x_{p}}_{3}')]])), Immuta

In [23]:
print(*val[0])

1.0 10.0 100.0 1000.0


In [ ]:
import numpy as np
# sympy式とラムダ関数の定義
a, b, c, d = sp.symbols("a b c d")
func = sp.Matrix([0.1*b, 0.1*a, 0.1*d, 0.1*c])
arg_order = list(func.free_symbols)
#arg_order = [ b, a, c, d]
func_lamb = sp.lambdify(arg_order, func, "numpy")
# csvデータの読み取りと引数の順に並べ替え
csv_order = [a, b, c, d]
csv_data = """
1, 10, 100, 1000
2, 20, 200, 2000
3, 30, 300, 3000
"""
val = sct.setDataOrder(arg_order, csv_order, csv_data, isFile=False)

In [ ]:

import pandas as pd
import io

# sympy式とラムダ関数の定義
a, b, c, d = sp.symbols("a b c d")
func = sp.Matrix([0.1*b, 0.1*a, 0.1*d, 0.1*c])
arg_order = list(func.free_symbols)
#arg_order = [ b, a, c, d]
func_lamb = sp.lambdify(arg_order, func, "numpy")
# csvデータの読み取りと引数の順に並べ替え
csv_order = [a, b, c, d]
csv_data = """
1, 10, 100, 1000
2, 20, 200, 2000
3, 30, 300, 3000
"""
f = io.StringIO(csv_data.strip())
df = pd.read_csv(f, header=None, names=csv_order, skipinitialspace=True, dtype=float)
#df = pd.read_csv('data.csv', header=None, names=labels, skipinitialspace=True)
datadict = df.to_dict(orient='list')
ordered_values = [datadict[key] for key in arg_order]
val = [ list(d) for d in list(zip(*ordered_values))]
# 行ごとに計算
ans = [np.array(func_lamb(*v).reshape(len(arg_order))) for v in val]



[b, a, c, d]

[a, b, c, d]

[[10.0, 20.0, 30.0], [1.0, 2.0, 3.0], [100.0, 200.0, 300.0], [1000.0, 2000.0, 3000.0]]
[[10.0, 1.0, 100.0, 1000.0], [20.0, 2.0, 200.0, 2000.0], [30.0, 3.0, 300.0, 3000.0]]


In [25]:
func_lamb(*val[0]).reshape(4)

array([  1. ,   0.1, 100. ,  10. ])

In [26]:
fc = sp.Matrix([[0.1*b, 0.1*a, 0.1*d, 0.1*c]])
fa = list(fc.free_symbols)
ful = sp.lambdify(fa, fc, 'numpy')
ov = [[10.0, 20.0, 30.0], [1.0, 2.0, 3.0], [1000.0, 2000.0, 3000.0], [100.0, 200.0, 300.0]]
print(ful(*ov))

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
import sympy as sp
import numpy as np # NumPyバックエンドを使うためインポート（必須ではないが分かりやすさのため）

# 1. シンボルを定義
a, b, c, d = sp.symbols('a b c d')

# 2. SymPyのMatrixを定義
fc = sp.Matrix([0.2*b +  a, 0.2*a, 0.2*d, 0.2*c])

# 3. (修正点 1) 引数の順序を明示的に定義
# list(fc.free_symbols) は順序を保証しません。
# ov のデータ [b_vals, a_vals, d_vals, c_vals] の順序に合わせます。
fa = [b, a, d, c]

# 4. (修正点 2) lambdifyのバックエンドに 'numpy' を指定
# これにより、リストやNumPy配列の要素ごとの計算が可能になります。
ful = sp.lambdify(fa, fc, modules='numpy')

# 5. 入力データ (列のリスト)
ov = np.array([[10.0, 20.0, 30.0], [1.0, 2.0, 3.0], [1000.0, 2000.0, 3000.0], [100.0, 200.0, 300.0]])
display(ov)
display(ov.shape)
# 6. 関数を実行
result = ful(*ov)
print(result)
print(result.shape)

array([[1.e+01, 2.e+01, 3.e+01],
       [1.e+00, 2.e+00, 3.e+00],
       [1.e+03, 2.e+03, 3.e+03],
       [1.e+02, 2.e+02, 3.e+02]])

(4, 3)

[[[3.e+00 6.e+00 9.e+00]]

 [[2.e-01 4.e-01 6.e-01]]

 [[2.e+02 4.e+02 6.e+02]]

 [[2.e+01 4.e+01 6.e+01]]]
(4, 1, 3)


In [ ]:
bps_identmat = sp.parse_expr("ImmutableDenseMatrix([[Mul(Symbol('{b_{m}}_{1;1}'), Symbol('{b_{m}}_{1;2}'), Add(Mul(Integer(-1), Symbol('{k_{x}}_{1;1}')), Symbol('{k_{x}}_{1;2}')), Pow(Add(Mul(Symbol('{b_{m}}_{1;1}'), Symbol('{b_{m}}_{2;2}'), Symbol('{k_{x}}_{1;1}'), Symbol('{k_{x}}_{1;2}')), Mul(Integer(-1), Symbol('{b_{m}}_{1;1}'), Symbol('{k_{u}}_{1;2}'), Symbol('{k_{x}}_{1;1}')), Mul(Integer(-1), Symbol('{b_{m}}_{1;2}'), Symbol('{b_{m}}_{2;1}'), Symbol('{k_{x}}_{1;1}'), Symbol('{k_{x}}_{1;2}')), Mul(Symbol('{b_{m}}_{1;2}'), Symbol('{k_{u}}_{1;1}'), Symbol('{k_{x}}_{1;2}'))), Integer(-1)))], [Mul(Add(Mul(Symbol('{b_{m}}_{1;1}'), Symbol('{b_{m}}_{2;2}'), Symbol('{k_{x}}_{1;2}')), Mul(Integer(-1), Symbol('{b_{m}}_{1;1}'), Symbol('{k_{u}}_{1;2}')), Mul(Integer(-1), Symbol('{b_{m}}_{1;2}'), Symbol('{b_{m}}_{2;1}'), Symbol('{k_{x}}_{1;1}')), Mul(Symbol('{b_{m}}_{1;2}'), Symbol('{k_{u}}_{1;1}'))), Pow(Add(Mul(Symbol('{b_{m}}_{1;1}'), Symbol('{b_{m}}_{2;2}'), Symbol('{k_{x}}_{1;1}'), Symbol('{k_{x}}_{1;2}')), Mul(Integer(-1), Symbol('{b_{m}}_{1;1}'), Symbol('{k_{u}}_{1;2}'), Symbol('{k_{x}}_{1;1}')), Mul(Integer(-1), Symbol('{b_{m}}_{1;2}'), Symbol('{b_{m}}_{2;1}'), Symbol('{k_{x}}_{1;1}'), Symbol('{k_{x}}_{1;2}')), Mul(Symbol('{b_{m}}_{1;2}'), Symbol('{k_{u}}_{1;1}'), Symbol('{k_{x}}_{1;2}'))), Integer(-1)))]])")
aps_identmat = sp.parse_expr("ImmutableDenseMatrix([[Add(Mul(Integer(-1), Symbol('{a_{m}}_{2}'), Symbol('{b_{p}}_{2}'), Symbol('{k_{x}}_{1}')), Symbol('{a_{m}}_{2}'), Mul(Symbol('{a_{m}}_{4}'), Symbol('{b_{p}}_{1}'), Symbol('{k_{x}}_{1}')), Mul(Integer(-1), Symbol('{b_{p}}_{1}'), Symbol('{k_{x}}_{2}')))], [Add(Symbol('{a_{m}}_{4}'), Mul(Integer(-1), Symbol('{b_{p}}_{1}'), Symbol('{k_{x}}_{1}')), Mul(Integer(-1), Symbol('{b_{p}}_{2}'), Symbol('{k_{x}}_{2}')))]])")
dp(bps_identmat.free_symbols)